#!/bin/bash

# git executable wrapper script for Git-Mediawiki to run tests without
# installing all the scripts and perl packages.

ROOT_DIR=$(dirname "$0")/..

GITPERLLIB="$ROOT_DIR"

export GITPERLLIB

exec /usr/bin/git $@
